# Generated by Django 5.2 on 2025-06-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API_User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="large_url",
            field=models.JSONField(
                default=list, help_text="List of URLs for large-size images"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="medium_url",
            field=models.JSONField(
                default=list, help_text="List of URLs for medium-size images"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="small_url",
            field=models.JSONField(
                default=list, help_text="List of URLs for small-size images"
            ),
        ),
    ]
